---
# tasks file for alacritty

- name: install software using dnf
  ansible.builtin.package:
    name: "{{ alacritty_packages }}"
    state: present
    exclude: "{{ alacritty_exclude | default(omit) }}"
    allowerasing: yes
  when:
    - ansible_pkg_mgr == "dnf"

- name: install software using package
  ansible.builtin.package:
    name: "{{ alacritty_packages }}"
    state: present
  when:
    - ansible_pkg_mgr != "dnf"

- name: Push alacritty config
  ansible.builtin.copy:
    src: alacritty/
    dest: /home/{{ user.name }}/.config/alacritty/
    mode: "0755"
    owner: "{{ user.name }}"
    group: "{{ user.group | default(omit) }}"
